### ISSUE TITLE
Camera Picture Not as Expected

### ISSUE THREAD

**Issue by AshleySetter** [nqminds/nqm-irimager#88]
@aloisklink 

TWI have set up the camera pointing at a bright lamp to simulate a point source like so:
![20240131_120009](https://github.com/nqminds/nqm-irimager/assets/14869658/0339db70-f897-4b7e-99a2-35b7da4ac310)

However the array captured by the camera when plotted as an image (with imshow from matplotlib.pyplot) looks like so:
![image](https://github.com/nqminds/nqm-irimager/assets/14869658/c0953a7d-fdf9-443d-b847-192c6ebe2925)

My suspicion is that the pixels have been transposed in storing the data in an array, resulting in the line pattern we are seeing in the image.

I am using [a copy of the config file from this repository ](https://github.com/nqminds/iam3dpo-capture-server/blob/main/382x288%4027Hz.xml).

I have attached the array captured in this image to this issue as a .npy file compressed in a .zip folder (as github doesn't allow .npy files to be uploaded directory).
[2024-01-31 15:05:51.812048.zip](https://github.com/nqminds/nqm-irimager/files/14113511/2024-01-31.15.05.51.812048.zip)

**Comment by AshleySetter** [comment]
Simple solution, just needed reshaped to the opposite aspect ratio :face_exhaling: 
![image](https://github.com/nqminds/nqm-irimager/assets/14869658/d2d2cda3-6b9b-4fb3-8d9b-5825e7af7366)

**Comment by aloisklink** [comment]
:rocket:

Maybe I gambled incorrectly, and the data returned from the driver is column major, and not row major, if so, you can just replace `RowMajor` here with `ColMajor`: https://github.com/nqminds/nqm-irimager/blob/6130500743cdac95cf36a208527223dbc2f07ec1/src/nqm/irimager/irimager_class.hpp#L23-L26

Or maybe, we need to move around the `w` and `h` field in https://github.com/nqminds/nqm-irimager/blob/6130500743cdac95cf36a208527223dbc2f07ec1/src/nqm/irimager/irimager_class.cpp#L367 and https://github.com/nqminds/nqm-irimager/blob/6130500743cdac95cf36a208527223dbc2f07ec1/src/nqm/irimager/irimager_class.cpp#L67-L68
